server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.zhuzi.mallbase.model.entity    # 所有Entity别名类所在包
  mapper-locations:  classpath:mybatis/mapper/**/*.xml               # mapper映射文件

spring:
   application:
    name: mall-server-order
   datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver             # mysql驱动包
    url: jdbc:mysql://localhost:3306/db_order?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false #数据库名字
    username: root
    password: 123
    dbcp2:
      min-idle: 5                                           # 数据库连接池的最小维持连接数
      initial-size: 5                                       # 初始化连接数
      max-total: 5                                          # 最大连接数
      max-wait-millis: 200                                  # 等待连接获取的最大超时时间

eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:7001/eureka  #单机时  将此微服务注册进注册中心
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: mall-server-order   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址

feign:
  hystrix:
    enabled: true

info:
  app.name: mall-server-order
  company.name: www.liu.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$


#日志
#logging:
#  level:
#    com.sixstar.springcloudsixstarserverorder.mapper: debug
